spring.application.name=fraud-check-spring-api

fraud-check.amount-limit=5000.00
fraud-check.unusual-hours-start=22:00
fraud-check.unusual-hours-end=06:00
fraud-check.blocked-account-ids=acc-blocked

spring.web.locale=en
spring.web.locale-resolver=fixed